# Generated by Django 3.2.10 on 2022-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('img', models.FileField(max_length=64, upload_to='', verbose_name='图片')),
            ],
        ),
    ]
